trigger:
- master
- develop

stages:

- stage: 'Build'
  variables:
    buildConfiguration: 'Release'
    solutionPath: "DotNetCore.DI.Interception/DotNetCore.DI.Interception.sln"
    projectToPackPath: "DotNetCore.DI.Interception/DotNetCore.DI.Interception/DotNetCore.DI.Interception.csproj"

  jobs:
  - job:
    pool:
      vmImage: 'windows-latest'

    workspace:
      clean: all
  
    steps:
    # dotnet build
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build $(buildConfiguration)'
      inputs:
        command: 'build'
        projects: '$(solutionPath)'
        arguments: '--configuration  $(buildConfiguration)'

    # dotnet test
    - task: DotNetCoreCLI@2
      displayName: 'dotnet test $(buildConfiguration)'
      inputs:
        command: 'test'
        projects: '$(solutionPath)'
        arguments: '--configuration  $(buildConfiguration) --collect "Code coverage"'

    # dotnet pack
    - task: DotNetCoreCLI@2
      displayName: 'Create NuGet Package - Release Version'
      inputs:
        command: pack
        packagesToPack: '$(projectToPackPath)'
        packDirectory: '$(Build.ArtifactStagingDirectory)/packages/releases'
        arguments: '--configuration $(buildConfiguration)'
        nobuild: true 
    
    # publish the package in artifact directory
    - publish: '$(Build.ArtifactStagingDirectory)/packages'
      artifact: 'packages'

# Publish nuget when the branch is master
- stage: 'PublishReleaseNuGetPackage'
  displayName: 'Publish Release NuGet Package'
  dependsOn: 'Build'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment:
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'nuget-org'
    strategy:
     runOnce:
       deploy:
         steps:
         - task: NuGetCommand@2
           displayName: 'Push NuGet Package'
           inputs:
             command: 'push'
             packagesToPush: '$(Pipeline.Workspace)/packages/releases/*.nupkg'
             nuGetFeedType: 'external'
             publishFeedCredentials: 'NuGet'


